import { useEffect, useMemo, useState } from "react";
import { useJournal } from "../../hooks/useJournal";
import type { JournalTrade } from "../../types/journal";

const DB_NAME = "pal-trading-buddy-journal";
const STORE_NAME = "trade-screenshots";
const MAX_SCREENSHOTS = 4;
interface ScreenshotRecord { id: string; tradeId: number; name: string; type: string; dataUrl: string; createdAt: string; }

function openDb(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => { const db = request.result; if (!db.objectStoreNames.contains(STORE_NAME)) { const store = db.createObjectStore(STORE_NAME, { keyPath: "id" }); store.createIndex("tradeId", "tradeId", { unique: false }); } }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error ?? new Error("Could not open screenshot storage.")); }); }
async function readScreenshots(tradeId: number): Promise<ScreenshotRecord[]> { const db = await openDb(); return new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME, "readonly").objectStore(STORE_NAME).index("tradeId").getAll(tradeId); request.onsuccess = () => resolve((request.result as ScreenshotRecord[]).sort((a, b) => a.createdAt.localeCompare(b.createdAt))); request.onerror = () => reject(request.error ?? new Error("Could not read screenshots.")); }); }
async function writeScreenshot(record: ScreenshotRecord): Promise<void> { const db = await openDb(); return new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME, "readwrite").objectStore(STORE_NAME).put(record); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error ?? new Error("Could not save screenshot.")); }); }
async function deleteScreenshot(id: string): Promise<void> { const db = await openDb(); return new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME, "readwrite").objectStore(STORE_NAME).delete(id); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error ?? new Error("Could not delete screenshot.")); }); }
function fileToDataUrl(file: File): Promise<string> { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error ?? new Error("Could not read image.")); reader.readAsDataURL(file); }); }
function tradeLabel(trade: JournalTrade) { return `${trade.symbol} · ${trade.direction.toUpperCase()} · ${new Date(trade.exit_time).toLocaleString()}`; }
function resultClass(result: string) { const value = result.toUpperCase(); return value === "WIN" ? "border-emerald-400/15 bg-emerald-400/[0.07] text-emerald-300" : value === "LOSS" ? "border-red-400/15 bg-red-400/[0.07] text-red-300" : "border-white/[0.08] bg-white/[0.03] text-zinc-400"; }

export default function JournalScreenshots() {
    const { data } = useJournal(365);
    const trades = useMemo(() => data?.data?.trades ?? [], [data]);
    const [selectedId, setSelectedId] = useState<number | null>(null);
    const [screenshots, setScreenshots] = useState<ScreenshotRecord[]>([]);
    const [busy, setBusy] = useState(false);
    const [message, setMessage] = useState("");
    const [preview, setPreview] = useState<ScreenshotRecord | null>(null);
    useEffect(() => { if (selectedId == null && trades.length) setSelectedId(trades[0].position_id); }, [selectedId, trades]);
    useEffect(() => { if (selectedId == null) { setScreenshots([]); setPreview(null); return; } readScreenshots(selectedId).then((items) => { setScreenshots(items); setPreview(null); }).catch((error) => setMessage(error instanceof Error ? error.message : "Screenshot storage unavailable.")); }, [selectedId]);
    const selectedTrade = trades.find((trade) => trade.position_id === selectedId);
    async function addFiles(files: FileList | null) { if (!selectedId || !files?.length) return; const remaining = MAX_SCREENSHOTS - screenshots.length; const images = Array.from(files).filter((file) => ["image/png", "image/jpeg", "image/webp"].includes(file.type)).slice(0, remaining); if (!images.length) { setMessage("Use PNG, JPG or WEBP screenshots."); return; } setBusy(true); setMessage(""); try { const next: ScreenshotRecord[] = []; for (const file of images) { const record: ScreenshotRecord = { id: `${selectedId}-${Date.now()}-${Math.random().toString(36).slice(2)}`, tradeId: selectedId, name: file.name, type: file.type, dataUrl: await fileToDataUrl(file), createdAt: new Date().toISOString() }; await writeScreenshot(record); next.push(record); } setScreenshots((current) => [...current, ...next]); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save screenshot."); } finally { setBusy(false); } }
    async function remove(id: string) { await deleteScreenshot(id); setScreenshots((current) => current.filter((item) => item.id !== id)); if (preview?.id === id) setPreview(null); }
    return (
        <section className="mt-5 rounded-2xl border border-white/[0.08] bg-[#0a1110] p-5 shadow-[0_22px_70px_-45px_rgba(0,0,0,.95)] sm:p-6">
            <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between">
                <div><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.22em] text-emerald-300/70"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300" /> Trade Review</div><h2 className="mt-2 text-2xl font-semibold tracking-tight text-white">Chart Review</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-zinc-500">Keep the exact chart context behind your executions. Store up to four screenshots with every completed trade.</p></div>
                <div className="flex items-center gap-2"><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] px-4 py-2.5 text-right"><div className="text-[9px] uppercase tracking-[0.18em] text-zinc-600">Saved</div><div className="mt-0.5 text-sm font-semibold text-zinc-300">{screenshots.length} <span className="font-normal text-zinc-600">/ {MAX_SCREENSHOTS}</span></div></div><label className={`inline-flex cursor-pointer items-center justify-center rounded-xl border px-4 py-2.5 text-sm font-semibold transition ${screenshots.length >= MAX_SCREENSHOTS || busy || !selectedId ? "cursor-not-allowed border-white/[0.05] bg-white/[0.02] text-zinc-700" : "border-emerald-400/20 bg-emerald-400/10 text-emerald-200 hover:bg-emerald-400/15"}`}>{busy ? "Saving…" : "＋ Add chart"}<input type="file" accept="image/png,image/jpeg,image/webp" multiple className="hidden" disabled={screenshots.length >= MAX_SCREENSHOTS || busy || !selectedId} onChange={(event) => { void addFiles(event.target.files); event.currentTarget.value = ""; }} /></label></div>
            </div>
            <div className="mt-6 rounded-xl border border-white/[0.06] bg-black/20 p-4"><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end"><div><label className="mb-2 block text-[9px] font-semibold uppercase tracking-[0.2em] text-zinc-600">Review trade</label><select value={selectedId ?? ""} onChange={(event) => setSelectedId(Number(event.target.value))} className="w-full rounded-xl border border-white/[0.08] bg-zinc-950 px-4 py-3 text-sm text-zinc-200 outline-none transition focus:border-emerald-400/30"><option value="">Select a trade…</option>{trades.map((trade) => <option key={trade.position_id} value={trade.position_id}>{tradeLabel(trade)}</option>)}</select></div>{selectedTrade && <div className="flex items-center gap-2"><span className="rounded-lg border border-white/[0.07] bg-white/[0.025] px-3 py-2 text-[10px] uppercase tracking-wider text-zinc-500">{selectedTrade.direction}</span><span className={`rounded-lg border px-3 py-2 text-[10px] font-semibold uppercase tracking-wider ${resultClass(selectedTrade.result)}`}>{selectedTrade.result}</span></div>}</div></div>
            {message && <div className="mt-4 rounded-xl border border-amber-400/10 bg-amber-400/[0.04] px-4 py-3 text-sm text-amber-200/80">{message}</div>}
            <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{screenshots.map((shot, index) => <article key={shot.id} className="group overflow-hidden rounded-xl border border-white/[0.07] bg-[#070c0b] transition hover:border-emerald-300/20"><button type="button" onClick={() => setPreview(shot)} className="block w-full text-left"><div className="aspect-[4/3] bg-black"><img src={shot.dataUrl} alt={`Trade chart ${index + 1}`} className="h-full w-full object-contain transition duration-200 group-hover:scale-[1.015]" /></div><div className="border-t border-white/[0.06] p-3"><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-semibold uppercase tracking-[0.16em] text-emerald-300/60">Chart {String(index + 1).padStart(2, "0")}</span><span className="text-[9px] text-zinc-700">Open ↗</span></div><p className="mt-1 truncate text-xs text-zinc-400">{shot.name}</p></div></button><div className="flex items-center justify-between border-t border-white/[0.05] px-3 py-2"><span className="text-[9px] text-zinc-700">{new Date(shot.createdAt).toLocaleDateString()}</span><button type="button" onClick={() => void remove(shot.id)} className="rounded-md px-2 py-1 text-[9px] font-semibold uppercase tracking-wider text-red-300/70 hover:bg-red-400/10 hover:text-red-300">Remove</button></div></article>)}{!screenshots.length && <div className="md:col-span-2 xl:col-span-4 rounded-xl border border-dashed border-white/[0.07] bg-white/[0.015] px-6 py-12 text-center"><div className="mx-auto flex h-11 w-11 items-center justify-center rounded-xl border border-white/[0.07] bg-white/[0.025] text-lg text-zinc-600">⌁</div><h3 className="mt-3 text-sm font-semibold text-zinc-400">No chart screenshots yet</h3><p className="mt-1 text-xs text-zinc-600">Select a trade above, then add your entry, management or exit charts.</p></div>}</div>
            {preview && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-5 backdrop-blur-sm" role="dialog" aria-modal="true"><button type="button" aria-label="Close preview" onClick={() => setPreview(null)} className="absolute inset-0 cursor-default" /><div className="relative z-10 max-h-[92vh] w-full max-w-6xl overflow-hidden rounded-2xl border border-white/[0.1] bg-[#080d0c] shadow-2xl"><div className="flex items-center justify-between border-b border-white/[0.07] px-4 py-3"><div><div className="text-[9px] uppercase tracking-[0.2em] text-emerald-300/60">Chart preview</div><div className="mt-1 max-w-[70vw] truncate text-sm text-zinc-300">{preview.name}</div></div><button type="button" onClick={() => setPreview(null)} className="rounded-lg border border-white/[0.07] px-3 py-1.5 text-xs text-zinc-400 hover:text-white">Close</button></div><div className="max-h-[78vh] overflow-auto bg-black p-3"><img src={preview.dataUrl} alt="Full trade chart preview" className="mx-auto max-h-[74vh] w-auto max-w-full object-contain" /></div></div></div>}
        </section>
    );
}
