import { useMemo, useState } from "react";
import { useJournal } from "../hooks/useJournal";
import type { JournalTrade } from "../types/journal";

type Period = 7 | 30 | 90 | 365;
type ResultFilter = "ALL" | "WIN" | "LOSS" | "BREAKEVEN";

const money = (v: number) => `${v >= 0 ? "+" : "-"}$${Math.abs(v).toFixed(2)}`;
const plainMoney = (v: number) => `$${Math.abs(v).toFixed(2)}`;
const isWin = (t: JournalTrade) => t.result.toUpperCase() === "WIN";
const isLoss = (t: JournalTrade) => t.result.toUpperCase() === "LOSS";
const isBE = (t: JournalTrade) => t.result.toUpperCase() === "BREAKEVEN" || t.net_profit === 0;
const date = (v: string) => { const d = new Date(v); return Number.isNaN(d.getTime()) ? "—" : d.toLocaleDateString(undefined, { month: "short", day: "2-digit", year: "numeric" }); };
const shortDate = (v: string) => { const d = new Date(v); return Number.isNaN(d.getTime()) ? "—" : d.toLocaleDateString(undefined, { month: "short", day: "numeric" }); };

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) {
    return <section className={`overflow-hidden rounded-2xl border border-white/[0.07] bg-[#081411]/90 shadow-[0_18px_55px_rgba(0,0,0,.22)] ${className}`}>{children}</section>;
}
function Header({ period, setPeriod, symbol, setSymbol, result, setResult, symbols, onRefresh, refreshing }: any) {
    return <>
        <div className="mb-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
            <div><p className="text-[10px] font-semibold uppercase tracking-[0.32em] text-emerald-300/75">Trading Journal</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-[34px]">Record and analyze your trades, emotions, and market conditions</h1><p className="mt-1 text-sm text-zinc-500">A professional view of performance, execution quality and repeatable edge.</p></div>
            <div className="flex flex-wrap gap-2">
                <select value={period} onChange={(e) => setPeriod(Number(e.target.value))} className="rounded-lg border border-white/[0.07] bg-[#091713] px-3 py-2 text-[10px] text-zinc-400 outline-none"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last quarter</option><option value={365}>Last year</option></select>
                <select value={symbol} onChange={(e) => setSymbol(e.target.value)} className="rounded-lg border border-white/[0.07] bg-[#091713] px-3 py-2 text-[10px] text-zinc-400 outline-none"><option value="ALL">All symbols</option>{symbols.map((s: string) => <option key={s} value={s}>{s}</option>)}</select>
                <select value={result} onChange={(e) => setResult(e.target.value)} className="rounded-lg border border-white/[0.07] bg-[#091713] px-3 py-2 text-[10px] text-zinc-400 outline-none"><option value="ALL">All results</option><option value="WIN">Wins</option><option value="LOSS">Losses</option><option value="BREAKEVEN">Breakeven</option></select>
                <button onClick={onRefresh} disabled={refreshing} className="rounded-lg border border-emerald-400/15 bg-emerald-400/[0.07] px-3 py-2 text-[10px] font-semibold text-emerald-300 hover:bg-emerald-400/[0.12]">{refreshing ? "Refreshing…" : "↻ Refresh"}</button>
            </div>
        </div>
    </>;
}
function Stat({ label, value, sub, accent = "text-white" }: { label: string; value: string; sub: string; accent?: string }) {
    return <Card className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-wider text-zinc-600">{label}</div><div className={`mt-2 text-2xl font-semibold tracking-tight ${accent}`}>{value}</div><div className="mt-1 text-[10px] text-zinc-600">{sub}</div></div><div className="h-9 w-9 rounded-full border border-white/[0.06] bg-white/[0.02]" /></div></Card>;
}
function Equity({ trades, starting }: { trades: JournalTrade[]; starting: number }) {
    const sorted = [...trades].sort((a,b) => new Date(a.exit_time).getTime()-new Date(b.exit_time).getTime());
    if (!sorted.length) return <Card className="p-5"><div className="text-sm font-semibold">Equity Curve</div><div className="flex h-56 items-center justify-center text-sm text-zinc-600">No trades match the current filters.</div></Card>;
    let balance = starting; const points = [{ balance, time: sorted[0].entry_time }]; sorted.forEach(t => { balance += t.net_profit; points.push({ balance, time: t.exit_time }); });
    const min = Math.min(...points.map(p=>p.balance)); const max = Math.max(...points.map(p=>p.balance)); const range = Math.max(1, max-min); const w=900,h=250,p=24; const coords=points.map((pt,i)=>({x:p+(i/Math.max(1,points.length-1))*(w-p*2),y:p+(1-(pt.balance-min)/range)*(h-p*2)})); const line=coords.map((c,i)=>`${i?'L':'M'} ${c.x} ${c.y}`).join(" "); const area=`${line} L ${coords.at(-1)!.x} ${h-p} L ${coords[0].x} ${h-p} Z`;
    return <Card className="p-5"><div className="flex items-start justify-between"><div><div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600">Performance</div><h2 className="mt-1 text-lg font-semibold">Equity Curve</h2></div><span className={`text-sm font-semibold ${balance-starting>=0?'text-emerald-400':'text-red-400'}`}>{money(balance-starting)}</span></div><div className="mt-4 rounded-xl border border-white/[0.05] bg-black/20 p-3"><svg viewBox={`0 0 ${w} ${h}`} className="h-56 w-full" preserveAspectRatio="none"><line x1={p} y1={p} x2={w-p} y2={p} stroke="rgb(39 55 49)"/><line x1={p} y1={h/2} x2={w-p} y2={h/2} stroke="rgb(39 55 49)"/><line x1={p} y1={h-p} x2={w-p} y2={h-p} stroke="rgb(39 55 49)"/><path d={area} fill="rgb(20 184 166)" fillOpacity=".08"/><path d={line} fill="none" stroke="rgb(45 212 191)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>{coords.map((c,i)=><circle key={i} cx={c.x} cy={c.y} r="3" fill="rgb(45 212 191)"/> )}</svg><div className="flex justify-between text-[9px] text-zinc-700"><span>{shortDate(points[0].time)}</span><span>Starting {plainMoney(starting)}</span><span>{shortDate(points.at(-1)!.time)}</span></div></div></Card>;
}
function AIOverview({ trades, net, winRate }: { trades: JournalTrade[]; net: number; winRate: number }) {
    const winners = trades.filter(isWin); const best = [...trades].sort((a,b)=>b.net_profit-a.net_profit)[0];
    const avgWin = winners.length ? winners.reduce((s,t)=>s+t.net_profit,0)/winners.length : 0;
    return <Card className="p-5"><div className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[0.18em] text-cyan-300/80">✦ AI performance overview</div><h2 className="mt-2 text-xl font-semibold">{net >= 0 ? "Your journal is showing a positive edge" : "Your journal needs tighter risk control"}</h2><p className="mt-2 text-xs leading-5 text-zinc-500">Across {trades.length} completed trades, net P&L is {money(net)} with a {winRate.toFixed(1)}% win rate. {best ? `${best.symbol} produced the strongest single result at ${money(best.net_profit)}.` : "Keep logging trades to build a reliable performance sample."}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-cyan-300/10 bg-cyan-300/[0.035] p-3"><div className="text-[9px] font-semibold text-cyan-200">Focus actions</div><p className="mt-2 text-[11px] leading-5 text-zinc-400">{winRate < 50 ? "Prioritize A+ setups and reduce marginal entries." : "Protect the current edge by keeping execution consistent."}</p><p className="mt-2 text-[11px] leading-5 text-zinc-400">Average winning trade: {plainMoney(avgWin)}.</p></div><div className="rounded-xl border border-emerald-300/10 bg-emerald-300/[0.035] p-3"><div className="text-[9px] font-semibold text-emerald-200">Strengths</div><p className="mt-2 text-[11px] leading-5 text-zinc-400">{winners.length ? `${winners.length} winning trades are contributing to the current equity curve.` : "No winning trades in the current filter."}</p></div></div></Card>;
}
function Heatmap({ trades }: { trades: JournalTrade[] }) { const map=useMemo(()=>{const m=new Map<string,number>(); trades.forEach(t=>{const d=new Date(t.exit_time); if(!Number.isNaN(d.getTime())){const k=d.toISOString().slice(0,10);m.set(k,(m.get(k)||0)+t.net_profit)}});return m},[trades]); const days=Array.from({length:35},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(34-i));return d.toISOString().slice(0,10)}); return <Card className="p-5"><div className="flex justify-between"><div><div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600">Activity</div><h2 className="mt-1 text-lg font-semibold">Performance Heatmap</h2></div><span className="text-[9px] text-zinc-700">Last 5 weeks</span></div><div className="mt-5 grid grid-cols-7 gap-2">{days.map(k=>{const v=map.get(k)||0; const cls=!map.has(k)?"bg-white/[0.025] border-white/[0.04]":v>0?"bg-emerald-400/70 border-emerald-300/30":v<0?"bg-red-400/60 border-red-300/20":"bg-zinc-700 border-zinc-600";return <div key={k} title={`${k}: ${money(v)}`} className={`h-7 rounded-md border ${cls}`} />})}</div><div className="mt-4 flex justify-between text-[9px] text-zinc-700"><span>Less activity</span><span>Profit / loss intensity</span><span>More activity</span></div></Card>; }
function DayPerformance({ trades }: { trades: JournalTrade[] }) { const days=["Mon","Tue","Wed","Thu","Fri"]; const values=days.map((name,i)=>{const pnl=trades.filter(t=>{const d=new Date(t.exit_time);return d.getDay()===i+1}).reduce((s,t)=>s+t.net_profit,0);return {name,pnl}});const max=Math.max(1,...values.map(v=>Math.abs(v.pnl))); return <Card className="p-5"><div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600">Performance</div><h2 className="mt-1 text-lg font-semibold">P&L by Day of Week</h2><div className="mt-5 flex h-48 items-end justify-between gap-3 border-b border-white/[0.06] px-2">{values.map(v=><div key={v.name} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className={`w-full max-w-10 rounded-t-md ${v.pnl>=0?'bg-emerald-400/70':'bg-red-400/65'}`} style={{height:`${Math.max(5,Math.abs(v.pnl)/max*82)}%`}} title={money(v.pnl)} /><span className="text-[9px] text-zinc-600">{v.name}</span></div>)}</div></Card>; }
function TradeQuality({ trades }: { trades: JournalTrade[] }) { const score=(condition:boolean)=>condition?Math.min(10,6+trades.filter(condition ? isWin : isLoss).length/Math.max(1,trades.length)*4):5; const vals=[score(trades.length>0),score(trades.length>0),score(trades.length>0),score(trades.length>0),score(trades.length>0)]; return <Card className="p-5"><div className="flex justify-between"><div><div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600">Execution</div><h2 className="mt-1 text-lg font-semibold">Trade Quality</h2></div><span className="rounded-full bg-cyan-400/10 px-2 py-1 text-[9px] text-cyan-300">{(vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(1)} / 10</span></div><div className="mt-5 space-y-3">{["Entry Timing","Exit Timing","Risk Mgmt","Discipline","Execution"].map((label,i)=><div key={label}><div className="mb-1 flex justify-between text-[9px] text-zinc-600"><span>{label}</span><span>{vals[i].toFixed(1)}</span></div><div className="h-1.5 rounded-full bg-zinc-900"><div className="h-full rounded-full bg-cyan-300/70" style={{width:`${vals[i]*10}%`}} /></div></div>)}</div></Card>; }
function RecentTrades({ trades }: { trades: JournalTrade[] }) { const [show,setShow]=useState(false); const visible=show?trades:trades.slice(0,6); return <Card className="p-5"><div className="flex items-center justify-between"><div><div className="text-[9px] uppercase tracking-[0.2em] text-zinc-600">Journal</div><h2 className="mt-1 text-lg font-semibold">Recent Trades</h2></div><button onClick={()=>setShow(!show)} className="text-[10px] text-zinc-500 hover:text-white">{show?'Show less':'View all →'}</button></div><div className="mt-4 divide-y divide-white/[0.05]">{visible.map(t=><div key={t.position_id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div className="flex items-center gap-3"><span className={`text-sm ${t.net_profit>=0?'text-emerald-400':'text-red-400'}`}>{t.net_profit>=0?'＋':'−'}</span><div><div className="text-xs font-semibold text-zinc-200">{t.symbol}</div><div className="mt-0.5 text-[9px] uppercase tracking-wider text-zinc-700">{t.direction} · {date(t.exit_time)}</div></div></div><div className="text-right"><div className={`text-xs font-semibold ${t.net_profit>=0?'text-emerald-400':'text-red-400'}`}>{money(t.net_profit)}</div><div className="text-[9px] text-zinc-700">{t.result}</div></div></div>)}{!visible.length&&<div className="py-8 text-center text-sm text-zinc-600">No trades match the current filters.</div>}</div></Card>; }

export default function JournalProfessional() {
    const { data: response, isLoading, isError, error, refetch, isFetching } = useJournal(365);
    const [period,setPeriod]=useState<Period>(90); const [symbol,setSymbol]=useState("ALL"); const [result,setResult]=useState<ResultFilter>("ALL");
    const allTrades=(response?.data?.trades ?? []) as JournalTrade[]; const symbols=useMemo(()=>Array.from(new Set(allTrades.map(t=>t.symbol))).sort(),[allTrades]);
    const filtered=useMemo(()=>{const cutoff=Date.now()-period*86400000;return allTrades.filter(t=>{const time=new Date(t.exit_time).getTime();return time>=cutoff&&(symbol==='ALL'||t.symbol===symbol)&&(result==='ALL'||(result==='WIN'&&isWin(t))||(result==='LOSS'&&isLoss(t))||(result==='BREAKEVEN'&&isBE(t)));});},[allTrades,period,symbol,result]);
    if(isLoading) return <div className="min-h-screen bg-[#06100d] p-8 text-white"><div className="mx-auto max-w-[1420px] rounded-2xl border border-white/[0.07] bg-[#081411] p-12 text-center"><div className="text-lg font-semibold">Loading Trading Journal…</div><div className="mt-2 text-sm text-zinc-600">Reading the latest MT5 data.</div></div></div>;
    if(isError||!response?.success||!response.data) return <div className="min-h-screen bg-[#06100d] p-8 text-white"><div className="mx-auto max-w-[1420px] rounded-2xl border border-red-400/10 bg-[#081411] p-12 text-center"><div className="text-lg font-semibold text-red-300">Unable to load journal</div><p className="mt-2 text-sm text-zinc-500">{error instanceof Error?error.message:'The journal API returned an error.'}</p><button onClick={()=>void refetch()} className="mt-5 rounded-lg bg-white/[0.06] px-4 py-2 text-sm">Try again</button></div></div>;
    const net=filtered.reduce((s,t)=>s+t.net_profit,0); const wins=filtered.filter(isWin).length; const losses=filtered.filter(isLoss).length; const winRate=filtered.length?wins/filtered.length*100:0; const grossWin=filtered.filter(t=>t.net_profit>0).reduce((s,t)=>s+t.net_profit,0); const grossLoss=Math.abs(filtered.filter(t=>t.net_profit<0).reduce((s,t)=>s+t.net_profit,0)); const pf=grossLoss?grossWin/grossLoss:0; const avgWin=wins?grossWin/wins:0; const avgLoss=losses?grossLoss/losses:0; const starting=(response.data.account?.balance ?? 0)-net;
    return <div className="min-h-screen bg-[#06100d] text-white"><main className="mx-auto max-w-[1420px] px-4 py-6 sm:px-6 lg:px-8"><Header {...{period,setPeriod,symbol,setSymbol,result,setResult,symbols,onRefresh:()=>void refetch(),refreshing:isFetching}}/><div className="mb-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Stat label="Net P&L" value={money(net)} sub={`${filtered.length} completed trades`} accent={net>=0?'text-emerald-400':'text-red-400'}/><Stat label="Profit Factor" value={pf?pf.toFixed(2):'—'} sub={`${plainMoney(grossWin)} gross profit`} accent="text-cyan-300"/><Stat label="Win Rate" value={`${winRate.toFixed(1)}%`} sub={`${wins} wins · ${losses} losses`} accent="text-white"/><Stat label="Avg Win / Loss" value={avgLoss?`${(avgWin/avgLoss).toFixed(1)}x`:'—'} sub={`${plainMoney(avgWin)} avg win · ${plainMoney(avgLoss)} avg loss`} accent="text-white"/></div><div className="grid gap-4 xl:grid-cols-[1fr_1.35fr]"><Equity trades={filtered} starting={starting}/><AIOverview trades={filtered} net={net} winRate={winRate}/></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><Heatmap trades={filtered}/><DayPerformance trades={filtered}/><TradeQuality trades={filtered}/></div><div className="mt-4"><RecentTrades trades={filtered}/></div></main></div>;
}
