import { useMemo, useState } from "react";
import PalPageShell from "../components/layout/PalPageShell";
import type { Page } from "../components/layout/Sidebar";
import { usePAL } from "../hooks/usePAL";

type Props = { onPageChange: (page: Page) => void };
type EventItem = Record<string, unknown>;
type Range = "TODAY" | "TOMORROW" | "ALL";

function text(event: EventItem, keys: string[]) { for (const key of keys) { const value = event[key]; if (value !== undefined && value !== null && String(value).trim()) return String(value); } return "—"; }
function eventDate(event: EventItem) { const raw = text(event, ["time", "scheduled_time", "datetime", "date"]); if (raw === "—") return null; const parsed = new Date(raw); return Number.isNaN(parsed.getTime()) ? null : parsed; }
function matchesRange(event: EventItem, range: Range) { if (range === "ALL") return true; const date = eventDate(event); if (!date) return false; const now = new Date(); const start = new Date(now.getFullYear(), now.getMonth(), now.getDate()); if (range === "TOMORROW") start.setDate(start.getDate() + 1); const end = new Date(start); end.setDate(start.getDate() + 1); return date >= start && date < end; }
function impactClass(value: string) { const impact = value.toUpperCase(); if (impact.includes("HIGH")) return "border-red-400/20 bg-red-400/[0.07] text-red-300"; if (impact.includes("MEDIUM")) return "border-amber-400/20 bg-amber-400/[0.07] text-amber-300"; return "border-zinc-700/60 bg-zinc-900/60 text-zinc-500"; }
function impactDot(value: string) { const impact = value.toUpperCase(); if (impact.includes("HIGH")) return "bg-red-400 shadow-[0_0_9px_rgba(248,113,113,.7)]"; if (impact.includes("MEDIUM")) return "bg-amber-300 shadow-[0_0_9px_rgba(252,211,77,.6)]"; return "bg-zinc-600"; }
function formatTime(raw: string) { const date = new Date(raw); if (Number.isNaN(date.getTime())) return raw; return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }); }
function formatDate(raw: string) { const date = new Date(raw); if (Number.isNaN(date.getTime())) return "Upcoming"; return date.toLocaleDateString([], { weekday: "short", month: "short", day: "numeric" }); }

export default function MacroCalendar({ onPageChange }: Props) {
    const { data, isLoading } = usePAL();
    const [currency, setCurrency] = useState("ALL");
    const [impact, setImpact] = useState("ALL");
    const [range, setRange] = useState<Range>("ALL");
    const events = useMemo(() => {
        const raw = [...(data?.report?.news?.upcoming_events ?? []), ...(data?.report?.news?.recent_events ?? [])] as EventItem[];
        const seen = new Set<string>();
        return raw.filter((event) => { const title = text(event, ["title", "name", "event"]); const time = text(event, ["time", "scheduled_time", "datetime", "date"]); const eventCurrency = text(event, ["currency", "ccy"]).toUpperCase(); const eventImpact = text(event, ["impact", "importance"]).toUpperCase(); const key = `${title}|${time}|${eventCurrency}|${eventImpact}`; if (seen.has(key)) return false; seen.add(key); if (currency !== "ALL" && eventCurrency !== currency) return false; if (impact !== "ALL" && !eventImpact.includes(impact)) return false; return matchesRange(event, range); });
    }, [data, currency, impact, range]);
    const highCount = events.filter((event) => text(event, ["impact", "importance"]).toUpperCase().includes("HIGH")).length;
    const mediumCount = events.filter((event) => text(event, ["impact", "importance"]).toUpperCase().includes("MEDIUM")).length;
    return (
        <PalPageShell page="macro-calendar" onPageChange={onPageChange}>
            <div className="min-h-screen bg-[#06100d] text-white"><main className="mx-auto max-w-[1420px] px-4 py-6 sm:px-6 lg:px-8">
                <header className="mb-5"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.34em] text-emerald-300/70">Macro Calendar</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-[36px]">What Matters Next</h1><p className="mt-1 text-sm text-zinc-500">A premium event map for rates, currencies, risk and session preparation.</p></div><div className="flex items-center gap-2 rounded-xl border border-white/[0.07] bg-[#091712]/90 px-4 py-3"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300 shadow-[0_0_10px_rgba(110,231,183,.8)]"/><span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-zinc-500">Live provider calendar</span></div></div></header>
                <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/[0.07] bg-[#091712] p-4"><p className="text-[9px] uppercase tracking-[0.2em] text-zinc-600">Events in view</p><p className="mt-2 text-2xl font-semibold text-white">{events.length}</p><p className="mt-1 text-[10px] text-zinc-600">Provider-supplied releases</p></div><div className="rounded-2xl border border-red-400/10 bg-red-400/[0.025] p-4"><p className="text-[9px] uppercase tracking-[0.2em] text-red-300/50">High impact</p><p className="mt-2 text-2xl font-semibold text-red-300">{highCount}</p><p className="mt-1 text-[10px] text-zinc-600">Potential volatility catalysts</p></div><div className="rounded-2xl border border-amber-400/10 bg-amber-400/[0.025] p-4"><p className="text-[9px] uppercase tracking-[0.2em] text-amber-300/50">Medium impact</p><p className="mt-2 text-2xl font-semibold text-amber-200">{mediumCount}</p><p className="mt-1 text-[10px] text-zinc-600">Secondary market drivers</p></div></section>
                <section className="mt-5 rounded-2xl border border-white/[0.07] bg-[#091310] p-4 shadow-[0_18px_50px_rgba(0,0,0,.25)]"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-cyan-300/70">Filters</p><p className="mt-1 text-xs text-zinc-600">Focus the calendar before entering London or New York.</p></div><div className="flex flex-wrap gap-2">{(["TODAY", "TOMORROW", "ALL"] as const).map((item) => <button key={item} type="button" onClick={() => setRange(item)} className={`rounded-lg border px-3 py-2 text-[10px] font-semibold uppercase tracking-wider transition ${range === item ? "border-emerald-400/25 bg-emerald-400/[0.09] text-emerald-200" : "border-white/[0.07] bg-white/[0.02] text-zinc-500 hover:text-zinc-300"}`}>{item}</button>)}<span className="mx-1 hidden h-8 w-px bg-white/[0.07] sm:block"/>{["ALL", "USD", "GBP", "EUR", "JPY"].map((item) => <button key={item} type="button" onClick={() => setCurrency(item)} className={`rounded-lg border px-3 py-2 text-[10px] font-semibold uppercase tracking-wider transition ${currency === item ? "border-cyan-400/25 bg-cyan-400/[0.08] text-cyan-200" : "border-white/[0.07] bg-white/[0.02] text-zinc-500 hover:text-zinc-300"}`}>{item}</button>)}<span className="mx-1 hidden h-8 w-px bg-white/[0.07] sm:block"/>{["ALL", "HIGH", "MEDIUM", "LOW"].map((item) => <button key={item} type="button" onClick={() => setImpact(item)} className={`rounded-lg border px-3 py-2 text-[10px] font-semibold uppercase tracking-wider transition ${impact === item ? "border-amber-400/25 bg-amber-400/[0.08] text-amber-200" : "border-white/[0.07] bg-white/[0.02] text-zinc-500 hover:text-zinc-300"}`}>{item}</button>)}</div></div></section>
                <section className="mt-5 rounded-2xl border border-white/[0.07] bg-[#091310] overflow-hidden"><div className="flex flex-col gap-3 border-b border-white/[0.06] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] uppercase tracking-[0.2em] text-emerald-300/60">Event stream</p><h2 className="mt-1 text-lg font-semibold">Upcoming market catalysts</h2></div><div className="rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-1.5 text-[10px] text-zinc-500">{isLoading ? "Refreshing…" : `${events.length} events`}</div></div><div className="divide-y divide-white/[0.05]">
                    {events.map((event, index) => { const title = text(event, ["title", "name", "event"]); const eventCurrency = text(event, ["currency", "ccy"]); const eventImpact = text(event, ["impact", "importance"]); const time = text(event, ["time", "scheduled_time", "datetime", "date"]); const actual = text(event, ["actual"]); const forecast = text(event, ["forecast"]); const previous = text(event, ["previous"]); return <article key={`${title}-${time}-${index}`} className="group grid gap-4 px-5 py-5 transition hover:bg-white/[0.018] lg:grid-cols-[155px_minmax(0,1fr)_240px]"><div className="flex gap-3 lg:block"><div className={`mt-1 h-2 w-2 shrink-0 rounded-full lg:mb-3 ${impactDot(eventImpact)}`}/><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-zinc-600">{formatDate(time)}</p><p className="mt-1 text-sm font-semibold text-zinc-300">{formatTime(time)}</p></div></div><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-md border border-white/[0.07] bg-white/[0.025] px-2 py-1 text-[9px] font-semibold tracking-wider text-zinc-500">{eventCurrency}</span><span className={`rounded-md border px-2 py-1 text-[9px] font-semibold uppercase tracking-wider ${impactClass(eventImpact)}`}>{eventImpact || "UNSPECIFIED"}</span></div><h3 className="mt-3 text-[15px] font-semibold leading-6 text-white">{title}</h3><p className="mt-1 text-[11px] leading-5 text-zinc-600">Macro release from the connected provider. Use the result alongside price structure and cross-asset confirmation.</p></div><div className="grid grid-cols-3 gap-2 lg:grid-cols-1"><div className="rounded-lg border border-white/[0.05] bg-black/20 px-3 py-2"><p className="text-[8px] uppercase tracking-[0.18em] text-zinc-700">Actual</p><p className="mt-1 text-xs font-medium text-zinc-300">{actual}</p></div><div className="rounded-lg border border-white/[0.05] bg-black/20 px-3 py-2"><p className="text-[8px] uppercase tracking-[0.18em] text-zinc-700">Forecast</p><p className="mt-1 text-xs font-medium text-zinc-300">{forecast}</p></div><div className="rounded-lg border border-white/[0.05] bg-black/20 px-3 py-2"><p className="text-[8px] uppercase tracking-[0.18em] text-zinc-700">Previous</p><p className="mt-1 text-xs font-medium text-zinc-300">{previous}</p></div></div></article>; })}
                    {!events.length && <div className="px-6 py-16 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl border border-white/[0.07] bg-white/[0.02] text-zinc-600">◫</div><h3 className="mt-4 text-sm font-semibold text-zinc-400">No events match these filters</h3><p className="mt-1 text-xs text-zinc-600">PAL will not fabricate calendar values when the provider has no matching release.</p></div>}
                </div></section>
                <div className="mt-4 flex items-center justify-between rounded-xl border border-white/[0.05] bg-white/[0.015] px-4 py-3 text-[9px] uppercase tracking-[0.16em] text-zinc-700"><span>Provider data only</span><span>Macro calendar · PAL Intelligence</span></div>
            </main></div>
        </PalPageShell>
    );
}
